# Generated by Django 3.0.3 on 2020-02-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_state', models.IntegerField(max_length=2)),
                ('level_name', models.CharField(max_length=100)),
                ('group', models.CharField(choices=[('01', 'อาหาร'), ('02', 'วัตถุอันตราย'), ('03', 'วัตถุออกฤทธิ์-วัตถุเสพติด'), ('04', 'ยา'), ('05', 'เครื่องสำอางค์'), ('06', 'เครื่องมือแพทย์')], max_length=2)),
                ('level_link', models.ManyToManyField(blank=True, null=True, to='info.Level')),
            ],
        ),
        migrations.DeleteModel(
            name='AllData',
        ),
    ]
