# Generated by Django 3.0.3 on 2020-02-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20200217_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=100)),
                ('document_file', models.FileField(upload_to='uploads/')),
                ('group', models.CharField(choices=[('01', 'อาหาร'), ('02', 'วัตถุอันตราย'), ('03', 'วัตถุออกฤทธิ์-วัตถุเสพติด'), ('04', 'ยา'), ('05', 'เครื่องสำอางค์'), ('06', 'เครื่องมือแพทย์')], max_length=2)),
            ],
        ),
    ]
