# Generated by Django 3.0.3 on 2020-02-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_link',
            field=models.ManyToManyField(to='info.Level'),
        ),
    ]
