# Generated by Django 3.0.3 on 2020-02-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_document_document_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_state',
            field=models.CharField(max_length=2),
        ),
    ]
