# Generated by Django 3.0.3 on 2020-04-02 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20200329_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='level',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 23, 50, 47, 939865)),
        ),
    ]
