# Generated by Django 3.0.3 on 2020-04-02 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20200402_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 0, 42, 22, 393961)),
        ),
        migrations.AlterField(
            model_name='level',
            name='rank',
            field=models.CharField(default='', max_length=3),
        ),
    ]
