# Generated by Django 3.0.3 on 2020-04-02 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20200403_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 0, 45, 7, 824865)),
        ),
        migrations.AlterField(
            model_name='level',
            name='rank',
            field=models.IntegerField(default='0'),
        ),
    ]
